<a href="https://colab.research.google.com/github/ApoorvaReddy17/practice/blob/main/Titanic_Dataset_Processing_Data_wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# creating Data Frame
import pandas as pd
df=pd.read_csv('titanic.csv')
df.head()

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0

In [2]:
# number of rows and columns
df.shape

(1313, 6)

In [3]:
# Data Frame Describing
df.describe()

              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [4]:
# Accessing first row
df.iloc[0]

Name        Allen, Miss Elisabeth Walton
PClass                               1st
Age                                 29.0
Sex                               female
Survived                               1
SexCode                                1
Name: 0, dtype: object

In [5]:
# selecting three rows
df.iloc[1:4]

,Name,PClass,Age,Sex,Survived,SexCode
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.0,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,1

In [6]:
# setting name column as index
df1=df.set_index(df['Name'])
df1.head()

,Name,PClass,Age,Sex,Survived,SexCode
Name,,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,2.00,female,0,1
"Allison, Mr Hudson Joshua Creighton","Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
"Allison, Master Hudson Trevor","Allison, Master Hudson Trevor",1st,0.92,male,1,0

In [7]:
# after setting Name as index, accessing first row
df1.loc['Allen, Miss Elisabeth Walton']

Name        Allen, Miss Elisabeth Walton
PClass                               1st
Age                                 29.0
Sex                               female
Survived                               1
SexCode                                1
Name: Allen, Miss Elisabeth Walton, dtype: object

In [8]:
# selecting rows based on condition
df1=df[df['Sex']=='female']
df1.head()

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.0,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,1
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,1
6,"Andrews, Miss Kornelia Theodosia",1st,63.0,female,1,1
8,"Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.0,female,1,1

In [9]:
# Selecting rows based on multiple conditions
df2=df[(df['Sex']=='female') & (df['Age']>=60)]
df2.head()

,Name,PClass,Age,Sex,Survived,SexCode
6,"Andrews, Miss Kornelia Theodosia",1st,63.0,female,1,1
38,"Bucknell, Mrs William Robert (Emma Eliza Ward)",1st,60.0,female,1,1
67,"Compton, Mrs Alexander Taylor (Mary Eliza Inge...",1st,64.0,female,1,1
73,"Crosby, Mrs Edward Gifford (Catherine Elizabet...",1st,69.0,female,1,1
104,"Fortune, Mrs Mark (Mary McDougald)",1st,60.0,female,1,1

In [10]:
# Replacing values
df3=df['Sex'].replace('female','Woman')
df3.head()

0    Woman
1    Woman
2     male
3    Woman
4     male
Name: Sex, dtype: object

In [11]:
# replacing values
df4=df['Sex'].replace(['female','male'],['Woman','Man'])
df4.head()

0    Woman
1    Woman
2      Man
3    Woman
4      Man
Name: Sex, dtype: object

In [12]:
df1=df.replace(1,"one")
df1.head()

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.0,female,one,one
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,one
2,"Allison, Mr Hudson Joshua Creighton",1st,30.0,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,one
4,"Allison, Master Hudson Trevor",1st,0.92,male,one,0

In [13]:
# renaming column names

df1= df.rename(columns={'Pclass':'Passenger Class','Sex':'Gender'})
df1.head()

,Name,PClass,Age,Gender,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0

In [14]:
# Finding min, max, mean, sum and count of Age column in DataFrame
print("maximum:",df['Age'].max())
print("minimum:",df['Age'].min())
print("mean:",df['Age'].mean())
print("sum:",df['Age'].sum())
print("count:",df['Age'].count())

maximum: 71.0
minimum: 0.17
mean: 30.397989417989418
sum: 22980.88
count: 756

In [15]:
# count of each column
df.count()

Name        1313
PClass      1313
Age          756
Sex         1313
Survived    1313
SexCode     1313
dtype: int64

In [16]:
# unique values in Sex column
df['Sex'].unique()

array(['female', 'male'], dtype=object)

In [17]:
# count of each value in sex column
df['Sex'].value_counts()

Sex
male      851
female    462
Name: count, dtype: int64

In [18]:
# count of each value in PClass column
df['PClass'].value_counts()

PClass
3rd    711
1st    322
2nd    279
*        1
Name: count, dtype: int64

In [19]:
# number of unique values in Pclass column
df['PClass'].nunique()

4

In [20]:
# checking null values
df.isnull().sum()

Name          0
PClass        0
Age         557
Sex           0
Survived      0
SexCode       0
dtype: int64

In [21]:
df[df['Age'].isnull()]

                              Name PClass  Age     Sex  Survived  SexCode
12    Aubert, Mrs Leontine Pauline    1st  NaN  female         1        1
13        Barkworth, Mr Algernon H    1st  NaN    male         1        0
14              Baumann, Mr John D    1st  NaN    male         0        0
29         Borebank, Mr John James    1st  NaN    male         0        0
32              Bradley, Mr George    1st  NaN    male         1        0
...                            ...    ...  ...     ...       ...      ...
1300         Wiseman, Mr Phillippe    3rd  NaN    male         0        0
1302             Yalsevac, Mr Ivan    3rd  NaN    male         1        0
1305            Youssef, Mr Gerios    3rd  NaN    male         0        0
1306           Zabour, Miss Hileni    3rd  NaN  female         0        1
1307           Zabour, Miss Tamini    3rd  NaN  female         0        1

[557 rows x 6 columns]

In [22]:
# Dropping the column
df.drop('Age',axis=1)

,Name,PClass,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,female,1,1
1,"Allison, Miss Helen Loraine",1st,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,female,0,1
4,"Allison, Master Hudson Trevor",1st,male,1,0
...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,male,0,0
1309,"Zakarian, Mr Maprieder",3rd,male,0,0
1310,"Zenni, Mr Philip",3rd,male,0,0
1311,"Lievens, Mr Rene",3rd,male,0,0
1312,"Zimmerman, Leo",3rd,male,0,0

In [23]:
# Dropping the columns
df.drop(['Age','Sex'],axis=1)

                                               Name PClass  Survived  SexCode
0                      Allen, Miss Elisabeth Walton    1st         1        1
1                       Allison, Miss Helen Loraine    1st         0        1
2               Allison, Mr Hudson Joshua Creighton    1st         0        0
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st         0        1
4                     Allison, Master Hudson Trevor    1st         1        0
...                                             ...    ...       ...      ...
1308                             Zakarian, Mr Artun    3rd         0        0
1309                         Zakarian, Mr Maprieder    3rd         0        0
1310                               Zenni, Mr Philip    3rd         0        0
1311                               Lievens, Mr Rene    3rd         0        0
1312                                 Zimmerman, Leo    3rd         0        0

[1313 rows x 4 columns]

In [24]:
# Dropping the column
df.drop(df.columns[1],axis=1)

,Name,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",29.00,female,1,1
1,"Allison, Miss Helen Loraine",2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",25.00,female,0,1
4,"Allison, Master Hudson Trevor",0.92,male,1,0
...,...,...,...,...,...
1308,"Zakarian, Mr Artun",27.00,male,0,0
1309,"Zakarian, Mr Maprieder",26.00,male,0,0
1310,"Zenni, Mr Philip",22.00,male,0,0
1311,"Lievens, Mr Rene",24.00,male,0,0
1312,"Zimmerman, Leo",29.00,male,0,0

In [25]:
# selecting data frame based on condition

df[df['Sex']!='male']

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.0,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,1
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,1
6,"Andrews, Miss Kornelia Theodosia",1st,63.0,female,1,1
8,"Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.0,female,1,1
...,...,...,...,...,...,...
1283,"Vestrom, Miss Hulda Amanda Adolfina",3rd,14.0,female,0,1
1293,"Wilkes, Mrs Ellen",3rd,45.0,female,1,1
1304,"Yasbeck, Mrs Antoni",3rd,15.0,female,1,1
1306,"Zabour, Miss Hileni",3rd,NaN,female,0,1
1307,"Zabour, Miss Tamini",3rd,NaN,female,0,1

In [26]:
# selecting Data Frame Based on condition
df[df['Name']!='Allison, Miss. Helen Loraine']

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
...,...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,27.00,male,0,0
1309,"Zakarian, Mr Maprieder",3rd,26.00,male,0,0
1310,"Zenni, Mr Philip",3rd,22.00,male,0,0
1311,"Lievens, Mr Rene",3rd,24.00,male,0,0
1312,"Zimmerman, Leo",3rd,29.00,male,0,0

In [27]:
# selecting dataframe based on condition
df[df.index !=0]

,Name,PClass,Age,Sex,Survived,SexCode
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
5,"Anderson, Mr Harry",1st,47.00,male,1,0
...,...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,27.00,male,0,0
1309,"Zakarian, Mr Maprieder",3rd,26.00,male,0,0
1310,"Zenni, Mr Philip",3rd,22.00,male,0,0
1311,"Lievens, Mr Rene",3rd,24.00,male,0,0
1312,"Zimmerman, Leo",3rd,29.00,male,0,0

In [28]:
# Applying groupby
df.groupby("Sex")[['Age','Survived']].mean()

              Age  Survived
Sex
female  29.396424  0.666667
male    31.014338  0.166863

In [29]:
df.groupby(['Survived','Sex','PClass'])[['Name']].count()

                        Name
Survived Sex    PClass
0        female 1st        9
                2nd       13
                3rd      132
         male   *          1
                1st      120
                2nd      147
                3rd      441
1        female 1st      134
                2nd       94
                3rd       80
         male   1st       59
                2nd       25
                3rd       58

In [30]:
df.groupby(['Sex','Survived']).count()

                 Name  PClass  Age  SexCode
Sex    Survived
female 0          154     154   71      154
       1          308     308  217      308
male   0          709     709  372      709
       1          142     142   96      142